---
- name: add ip
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
  - name: add ip address
    ios_config:
      authorize: yes
      parents: "int f0/1"
      lines:
          - ip add 10.10.10.1 255.255.255.0
          - no sh

- name: add ip
  hosts: R2
  gather_facts: false
  connection: network_cli

  tasks:
  - name: add ip address
    ios_config:
      authorize: yes
      parents: "int f0/1"
      lines:
          - ip add 10.10.10.2 255.255.255.0
          - no sh