---
- name: test backup
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
  - name: configurable backup path
    ios_config:
      backup: yes
      backup_options:
        filename: test_backup{{ inventory_hostname }}.cfg
        dir_path: /root/sdx/noj2
      register: output