---
- name: test restore
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
  - name: restore backup
    ios_config:
      src: ./backup_{{ inventory_hostname }}.cfg
      replace: config