---
- name: test restore
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    time: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"

  tasks:
  - name: restore backup
    ios_config:
      src: backup/backup_{{ inventory_hostname }}_{{ time }}.j2